### ISSUE TITLE
`dest_token` doesn't work if `dest_repo_github_api_url` and `src_repo_github_api_url` are the same

### ISSUE THREAD

**Issue by Legend-Master** [andrewthetechie/gha-clone-releases#206]
I'm trying to setup a repo on A to mirror releases to B with a setting like this

```yaml
token: ${{ secrets.GITHUB_TOKEN }}
dest_token: ${{ secrets.MIRROR_TO_REPO_B_TOKEN }}
src_repo: xxx/A
dest_repo: xxx/B
```

https://github.com/andrewthetechie/gha-clone-releases/blob/5670ac08048adecdcdffa0891f45d3415c6ffc6d/gha_clone_releases/main.py#L123-L127

Should be something like this

```python
dest_github = Github(inputs["dest_token"] or inputs["token"], base_url=inputs["dest_repo_github_api_url"])
```
